graph TD
    subgraph Команды
        TestClass1[AllTests]
    end

    TestClass1 --> |"chooseList"| ChooseClassTeam[Выбор команды]
    ChooseClassTeam --> |"checkbox"| CheckboxGroupSparta[Все тесты Sparta]
    CheckboxGroupSparta --> |"chooseList"| ChooseClassUiSparta[Выбор класса тестов функционала Sparta]
    CheckboxGroupSparta  --> |"checkbox"| CheckboxAllSpartaAPI[Все API тесты Sparta]
    CheckboxGroupSparta  --> |"checkbox"| CheckboxAllSpartaUI[Все UI тесты Sparta]
    CheckboxAllSpartaAPI --> |"checkbox"| CheckboxCritApiSparta[Крит API Sparta]
    CheckboxAllSpartaUI --> |"checkbox"| CheckboxCritUiSparta[Крит UI Sparta]
    ChooseClassTeam --> |"checkbox"| CheckboxGroupNorilsk[Все тесты Norilsk]
    CheckboxGroupNorilsk --> |"chooseList"| ChooseClassNorilsk[Выбор класса тестов функционала Norilsk]
    CheckboxGroupNorilsk  --> |"checkbox"| CheckboxAllNorilskAPI[Все API тесты Norilsk]
    CheckboxGroupNorilsk  --> |"checkbox"| CheckboxAllNorilskUI[Все UI тесты Norilsk]
    CheckboxAllNorilskAPI --> |"checkbox"| CheckboxCritApiNorilsk[Крит API Norilsk]
    CheckboxAllNorilskUI --> |"checkbox"| CheckboxCritUiNorilsk[Крит UI Norilsk]
    ChooseClassTeam --> |"checkbox"| CheckboxGroupUnderground[Все тесты Underground]
    CheckboxGroupUnderground --> |"chooseList"| ChooseClassUnderground[Выбор класса тестов функционала Underground]
    CheckboxGroupUnderground  --> |"checkbox"| CheckboxAllUndergroundAPI[Все API тесты Underground]
    CheckboxGroupUnderground  --> |"checkbox"| CheckboxAllUndergroundUI[Все UI тесты Underground]
    CheckboxAllUndergroundAPI --> |"checkbox"| CheckboxCritApiUnderground[Крит API Underground]
    CheckboxAllUndergroundUI --> |"checkbox"| CheckboxCritUiUnderground[Крит UI Underground]
    ChooseClassTeam --> |"checkbox"| CheckboxGroupDinero[Все тесты Dinero]
    CheckboxGroupDinero --> |"chooseList"| ChooseClassDinero[Выбор класса тестов функционала Dinero]
    CheckboxGroupDinero  --> |"checkbox"| CheckboxAllDineroAPI[Все API тесты Dinero]
    CheckboxGroupDinero  --> |"checkbox"| CheckboxAllDineroUI[Все UI тесты Dinero]
    CheckboxAllDineroAPI --> |"checkbox"| CheckboxCritApiDinero[Крит API Dinero]
    CheckboxAllDineroUI --> |"checkbox"| CheckboxCritUiDinero[Крит UI Dinero]